import { UserButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

const Home: NextPage = () => {
  const { user } = useUser()
  const [tab, setTab] = useState(0)
  const router = useRouter()

  console.log(user)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-[1200px] mx-auto p-6">
        <div className="flex justify-between items-center">
          <h1 className="text-3xl font-bold">T3 Blog App</h1>
          <div className="flex items-center gap-2">
            <h1 className="text-md" onClick={() => router.push(`/profile/${user?.id || ""}`)}>{user?.firstName}</h1>
            <UserButton afterSignOutUrl="/"/>
          </div>
        </div>
        <ul className="flex mt-12 gap-2">
          <li className={`text-[#bdc1c6] cursor-pointer p-3 rounded-md ${tab == 0 ? "text-white bg-white/10" : ""}`} onClick={() => setTab(0)}>For You</li>
          <li className={`text-[#bdc1c6] cursor-pointer p-3 rounded-md ${tab == 1 ? "text-white bg-white/10" : ""}`} onClick={() => setTab(1)}>Following</li>
        </ul>
        {
          tab == 0 ?
          [1,2,3,4,5].map(el => (
            <div className="p-4 bg-[#303134] rounded-md my-4 text-[#bdc1c6]" key={el} onClick={() => router.push(`/post/${el}`)}>
              <h1>Title</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime pariatur deleniti quisquam dolor corporis, iusto hic dolorem. Ipsum, vero expedita.</p>
            </div>
          ))
          :
          [1,2,3].map(el => (
            <div className="p-4 bg-[#303134] rounded-md my-4 text-[#bdc1c6]" key={el} onClick={() => router.push(`/post/${el}`)}>
              <h1>Title</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime pariatur deleniti quisquam dolor corporis, iusto hic dolorem. Ipsum, vero expedita.</p>
            </div>
          ))
        }
      </main>
    </>
  );
};

export default Home;