import { UserButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
// import { useState } from "react";
import { api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { Loader } from "~/components/Loader";
import { blurImage } from "~/utils/helper";
dayjs.extend(relativeTime);

const Home: NextPage = () => {
  const { user, isLoaded } = useUser()
  // const [tab, setTab] = useState(0)
  const router = useRouter()
  // const {data} = api.example.getPost.useQuery({id: "clid70vwx00009e400lifop3z"})
  const {data: allPost, isLoading} = api.post.getAllPost.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-[1200px] mx-auto p-6">
        <div className="flex justify-between items-center">
          <h1 className="text-3xl font-bold">T3 Blog App</h1>
          {isLoaded ? <div className="flex items-center gap-2">
            <h1 className="text-md" onClick={() => router.push(`/profile/${user?.id || ""}`)}>{user?.firstName}</h1>
            <UserButton afterSignOutUrl="/"/>
          </div> : <Loader />}
        </div>
        <ul className="flex mt-12 gap-2">
          {/* <li className={`text-[#bdc1c6] cursor-pointer p-3 rounded-md ${tab == 0 ? "text-white bg-white/10" : ""}`} onClick={() => setTab(0)}>For You</li>
          <li className={`text-[#bdc1c6] cursor-pointer p-3 rounded-md ${tab == 1 ? "text-white bg-white/10" : ""}`} onClick={() => setTab(1)}>Following</li> */}
          <li className={`text-[#bdc1c6] text-2xl rounded-md`}>My Feed</li>
        </ul>
          {
            isLoading ?
              <Loader />
            :
            <div className="grid grid-cols-1 gap-4 my-4">
              {
                allPost?.posts.map(el => (
                  <div className={`p-4 bg-[#303134] rounded-md text-[#bdc1c6] cursor-pointer`} key={el.id} onClick={() => router.push(`/post/${el.id || ""}`)}>
                    <div>
                      <div className="relative w-full min-h-[300px]">
                        <Image loading="lazy" src={el.image ?? ""} fill alt="image" className="rounded-md object-contain" placeholder="blur" blurDataURL={blurImage} />
                      </div>
                      <div className="my-4 flex justify-between items-center">
                        <h3 className="text-2xl">{el.title}</h3>
                        <p>{dayjs(el.createdAt).fromNow()}</p>
                      </div>
                      <p>{allPost?.users.find(user => user.id == el.authorId)?.name}</p>
                    </div>              
                  </div>
                ))
              }
            </div>
          }
      </main>
    </>
  );
};

export default Home;